export const Types = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    BOOKSHELF: 'BOOKSHELF',
    GETBOOKS: 'GETBOOKS',
    GETONEBOOK: 'GETONEBOOK',
    POSTNEWBOOK: 'POSTNEWBOOK',
    TO_PROFILE: 'TO_PROFILE',
    TO_MAIN: 'TO_MAIN'
}
